# Generated by Django 5.2.6 on 2025-09-16 15:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('mcp_session_id', models.CharField(blank=True, max_length=100, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System')], max_length=10)),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('error', 'Error')], default='completed', max_length=20)),
                ('model_used', models.CharField(blank=True, max_length=100)),
                ('tokens_used', models.IntegerField(blank=True, null=True)),
                ('mcp_operations', models.JSONField(blank=True, default=list)),
                ('error_message', models.TextField(blank=True)),
                ('trace_id', models.CharField(blank=True, max_length=100)),
                ('span_id', models.CharField(blank=True, max_length=100)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.chatsession')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='MCPOperation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('operation_type', models.CharField(choices=[('kv_get', 'KV Get'), ('kv_set', 'KV Set'), ('kv_mget', 'KV Multi-Get'), ('kv_del', 'KV Delete'), ('kv_ttl', 'KV TTL'), ('kv_scan', 'KV Scan'), ('store_find', 'Store Find'), ('store_aggregate', 'Store Aggregate'), ('session_appendEvent', 'Session Append Event'), ('capabilities_list', 'Capabilities List')], max_length=50)),
                ('parameters', models.JSONField(default=dict)),
                ('response', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('success', 'Success'), ('error', 'Error'), ('timeout', 'Timeout')], max_length=20)),
                ('duration_ms', models.IntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('error_details', models.TextField(blank=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='chat.chatmessage')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_ai_provider', models.CharField(choices=[('openai', 'OpenAI'), ('ollama', 'Ollama (Local)')], default='openai', max_length=20)),
                ('openai_model', models.CharField(default='gpt-3.5-turbo', max_length=50)),
                ('ollama_model', models.CharField(default='llama2', max_length=50)),
                ('max_tokens', models.IntegerField(default=1000)),
                ('temperature', models.FloatField(default=0.7)),
                ('theme', models.CharField(default='light', max_length=20)),
                ('show_timestamps', models.BooleanField(default=True)),
                ('show_token_usage', models.BooleanField(default=False)),
                ('show_mcp_operations', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chat_preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
