version: "3.9"
services:
  app:
    build: ..
    image: chat-datastore-mcp:local
    container_name: chat-datastore-app
    depends_on:
      - redis
      - mongodb
      - otel-collector
      - clickhouse
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/chatdb
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
    ports:
      - "8080:8080"
    networks:
      - chat_datastore_network

  redis:
    image: redis:7.2-alpine
    container_name: chat-datastore-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - chat_datastore_network

  mongodb:
    image: mongo:7.0
    container_name: chat-datastore-mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: adminpass
      MONGO_INITDB_DATABASE: chat-datastore
    volumes:
      - mongodb_data:/data/db
      - ./docker/mongodb/init:/docker-entrypoint-initdb.d
    networks:
      - chat_datastore_network

  clickhouse:
    image: clickhouse/clickhouse-server:24.8-alpine
    container_name: chat-datastore-clickhouse
    environment:
      - CLICKHOUSE_DB=otel
      - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1
    ports:
      - "8123:8123"   # HTTP
      - "9000:9000"   # Native
    volumes:
      - clickhouse_data:/var/lib/clickhouse
    networks:
      - chat_datastore_network

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.104.0
    container_name: chat-datastore-otel-collector
    command: ["--config=/etc/otelcol/config.yaml"]
    volumes:
      - otel_data:/data
      - ./otel-collector-config.yaml:/etc/otelcol/config.yaml:ro
    ports:
      - "4317:4317"   # OTLP gRPC
      - "4318:4318"   # OTLP HTTP
    depends_on:
      - clickhouse
    networks:
      - chat_datastore_network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
    container_name: chat-datastore-elasticsearch
    restart: always
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - http.cors.enabled=true
      - http.cors.allow-origin="*"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - chat_datastore_network

volumes:
  mongodb_data:
    driver: local
  elasticsearch_data:
    driver: local
  redis_data:
    driver: local
  otel_data:
    driver: local
  clickhouse_data:
    driver: local

networks:
  chat_datastore_network:
    driver: bridge
